[package]
authors = ["RSS Blue", "Dovydas Joksas"]
categories = ["parsing", "multimedia::audio"]
description = "Manage podcast chapters in Rust"
edition = "2021"
keywords = ["podcast"]
license = "MIT OR Apache-2.0"
name = "chapters"
readme = "README.md"
repository = "https://github.com/rssblue/chapters"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
chrono = "0.4.24"
id3 = "1.6.0"
regex = "1.7.3"
serde = {version="1.0.160", features=["derive"]}
serde_json = "1.0.95"
url = "2.3.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
